name       : ncmpcpp
version    : 0.8.1
release    : 17
homepage   : http://ncmpcpp.rybczak.net/
source     :
    - http://rybczak.net/ncmpcpp/stable/ncmpcpp-0.8.1.tar.bz2 : 4df9570a1db4ba2dc9b759aab88b283c00806fb5d2bce5f5d27a2eb10e6888ff
license    : GPL-2.0
component  : multimedia.audio
summary    : Featureful ncurses based MPD client inspired by ncmpc
description: |
    ncmpcpp is very similar to ncmpc if it comes to user interface, but it provides a lot of additional features.
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(icu-uc)
    - pkgconfig(libcurl)
    - pkgconfig(libmpdclient)
    - pkgconfig(taglib)
    - libboost-devel
    - readline-devel
setup      : |
    export BOOST_LIB_SUFFIX=""
    %configure --enable-outputs --enable-visualizer
build      : |
    %make
install    : |
    %make_install
