name       : ncmpcpp
version    : 0.7.4
release    : 3
homepage   : http://ncmpcpp.rybczak.net/
source     :
    - http://rybczak.net/ncmpcpp/stable/ncmpcpp-0.7.4.tar.bz2 : d70425f1dfab074a12a206ddd8f37f663bce2bbdc0a20f7ecf290ebe051f1e63
license    : GPL-2.0
component  : desktop.multimedia
summary    : Featureful ncurses based MPD client inspired by ncmpc
description: |
        ncmpcpp is very similar to ncmpc if it comes to user interface, but it provides a lot of additional features.
builddeps  :
    - pkgconfig(icu-uc)
    - pkgconfig(libmpdclient)
    - libboost-devel
    - readline-devel
setup      : |
    export BOOST_LIB_SUFFIX="" 
    %configure
build      : |
    %make
install    : |
    %make_install
