name       : ncmpcpp
version    : 0.7.1
release    : 2
homepage   : http://ncmpcpp.rybczak.net/
source     :
    - http://rybczak.net/ncmpcpp/stable/ncmpcpp-0.7.1.tar.bz2 : 73b76ca9a7b08b220c49251195b9a929768759bd03cf6956b74a2f218b2e2fdf
license    : GPL-2.0
summary    : Featureful ncurses based MPD client inspired by ncmpc
builddeps  :
    - libboost-devel
    - pkgconfig(libmpdclient)
    - pkgconfig(icu-uc)
    - readline-devel
description: |
        ncmpcpp is very similar to ncmpc if it comes to user interface, but it provides a lot of additional features.
setup      : |
    export BOOST_LIB_SUFFIX="" 
    %configure
build      : |
    %make
install    : |
    %make_install
