name       : ncmpcpp
version    : 0.7.5
release    : 5
homepage   : http://ncmpcpp.rybczak.net/
source     :
    - http://rybczak.net/ncmpcpp/stable/ncmpcpp-0.7.5.tar.bz2 : 7e4f643020b36698462879013a8b16111f8c3a4c5819cf186aed78032a41e07d
license    : GPL-2.0
component  : multimedia.audio
summary    : Featureful ncurses based MPD client inspired by ncmpc
description: |
    ncmpcpp is very similar to ncmpc if it comes to user interface, but it provides a lot of additional features.
builddeps  :
    - pkgconfig(icu-uc)
    - pkgconfig(libmpdclient)
    - libboost-devel
    - readline-devel
setup      : "export BOOST_LIB_SUFFIX=\"\" \n%configure\n"
build      : |
    %make
install    : |
    %make_install
