name       : ncmpcpp
version    : 0.8.2
release    : 20
homepage   : http://ncmpcpp.rybczak.net/
source     :
    - https://github.com/arybczak/ncmpcpp/archive/0.8.2.tar.gz : 682fa230029a917f8c8b54131e6c8fb4915aefed2cc5726ca7c3ab4f4fb97bda
license    : GPL-2.0
component  : multimedia.audio
summary    : Featureful ncurses based MPD client inspired by ncmpc
description: |
    ncmpcpp is very similar to ncmpc if it comes to user interface, but it provides a lot of additional features.
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(icu-uc)
    - pkgconfig(libcurl)
    - pkgconfig(libmpdclient)
    - pkgconfig(taglib)
    - libboost-devel
    - readline-devel
setup      : |
    export BOOST_LIB_SUFFIX=""
    %reconfigure --enable-outputs --enable-visualizer
build      : |
    %make
install    : |
    %make_install
