name       : ncmpcpp
version    : 0.8.0
release    : 11
homepage   : http://ncmpcpp.rybczak.net/
source     :
    - http://rybczak.net/ncmpcpp/stable/ncmpcpp-0.8.tar.bz2 : 2f0f2a1c0816119430880be6932e5eb356b7875dfa140e2453a5a802909f465a
license    : GPL-2.0
component  : multimedia.audio
summary    : Featureful ncurses based MPD client inspired by ncmpc
description: |
    ncmpcpp is very similar to ncmpc if it comes to user interface, but it provides a lot of additional features.
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(icu-uc)
    - pkgconfig(libcurl)
    - pkgconfig(libmpdclient)
    - pkgconfig(taglib)
    - libboost-devel
    - readline-devel
setup      : |
    export BOOST_LIB_SUFFIX=""
    %configure --enable-outputs --enable-visualizer
build      : |
    %make
install    : |
    %make_install
