name       : ncmpcpp
version    : 0.6.5
release    : 1
homepage   : http://ncmpcpp.rybczak.net/
source     :
    - http://ncmpcpp.rybczak.net/stable/ncmpcpp-0.6.5.tar.bz2 : 51128f6835c592c8d4367a66b08e06a9419a86c9d5c6e91d0f1dc73af56cd1fd
license    : GPL-2.0
summary    : Featureful ncurses based MPD client inspired by ncmpc
builddeps  :
    - libboost-devel 
description: |
        ncmpcpp is very similar to ncmpc if it comes to user interface, but it provides a lot of additional features.
setup      : |
    export BOOST_LIB_SUFFIX="" 
    ./autogen.sh
    %configure
build      : |
    %make
install    : |
    %make_install
